version: "3.8"

services:
  wordpress:
    image: ghcr.io/hansanghyeon/wordpress-redis:latest
    restart: always
    ports:
      - 30000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1
      WORDPRESS_DB_NAME: wp
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./src:/var/www/html/wp-content/themes/sage

  db:
    image: mariadb
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: wp
      MARIADB_ROOT_PASSWORD: 1

volumes:
  wordpress:
  redis:
