version: '3.7'
  
services:
  wordpress:
    env_file:
      - ./.env
    container_name: WP__${PROJECT_NAME}
    image: wordpress:php8.0
    restart: always
    environment:
      WORDPRESS_DB_HOST: workdb:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./src:/var/www/html/wp-content/themes/sage
    external_links:
      - DB__workwp:mariadb
    labels:
      - traefik.enable=true
      - traefik.http.routers.work-202110__${PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.work-202110__${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.demo.hyeon.pro`)
      - traefik.http.routers.work-202110__${PROJECT_NAME}.tls.certresolver=leresolver
      - traefik.http.services.work-202110__${PROJECT_NAME}.loadbalancer.server.port=80

########################### NETWORKS
networks:
  default:
    external:
      name: db_work
volumes:
  wordpress: