version: "3.8"

services:
  wordpress:
    env_file:
      - ./.env
    container_name: WP__${PROJECT_NAME}
    image: wordpress:6.0.1-php8.1-apache
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis */
        define('WP_REDIS_HOST', getenv_docker('WORDPRESS_REDIS_HOST', 'redis'));
        define('WP_REDIS_PORT', getenv_docker('WORDPRESS_REDIS_PORT', 6379));
    volumes:
      - ./.docker/wp:/var/www/html
      - ./apps/theme:/var/www/html/wp-content/themes/beeclover
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.svc__wordpress.rule=Host(`${PROJECT_NAME}.peterosea.com`)
      - traefik.http.routers.svc__wordpress.entrypoints=web
      - traefik.http.routers.svc__wordpress.entrypoints=websecure
      - traefik.http.routers.svc__wordpress.tls.certresolver=leresolver
      ## Service
      - traefik.http.services.svc__wordpress.loadbalancer.server.port=80

  db:
    image: mariadb
    container_name: DB__work
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: wp
      MARIADB_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./.docker/db/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: DB__phpmyadmin
    restart: always
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.svc__phpmyadmin.rule=Host(`phpmyadmin.${PROJECT_NAME}.beeclover.pro`)
      - traefik.http.routers.svc__phpmyadmin.entrypoints=web
      - traefik.http.routers.svc__phpmyadmin.entrypoints=websecure
      - traefik.http.routers.svc__phpmyadmin.tls.certresolver=leresolver
      ## Service
      - traefik.http.services.svc__phpmyadmin.loadbalancer.server.port=80

  redis:
    container_name: DB__redis
    image: redis:latest
    volumes:
      - redis:/data

  traefik:
    image: traefik:v2.8
    container_name: DO__traefik
    restart: unless-stopped
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./.docker/traefik/rules:/rules
      - ./.docker/traefik/acme:/acme
      - ./.docker/traefik/traefik.yaml:/etc/traefik/traefik.yaml
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.svc__traefik.rule=Host(`traefik.${PROJECT_NAME}.beeclover.pro`)
      - traefik.http.routers.svc__traefik.entrypoints=web
      - traefik.http.routers.svc__traefik.entrypoints=websecure
      - traefik.http.routers.svc__traefik.tls.certresolver=leresolver
      ## Service
      - traefik.http.services.svc__traefik.loadbalancer.server.port=8080

volumes:
  wordpress:
  redis:
