version: "3.8"

services:
  wordpress:
    env_file:
      - ./.env
    container_name: WP__${PROJECT_NAME}
    image: wordpress:php8.0
    restart: always
    ports:
      - ${PROJECT_PORT}:80
    environment:
      WORDPRESS_DB_HOST: workdb:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./src:/var/www/html/wp-content/themes/sage
    external_links:
      - DB__workwp:workdb

networks:
  default:
    external:
      name: db_work
volumes:
  wordpress:
