version: "3.8"

services:
  wordpress:
    image: ghcr.io/hansanghyeon/wordpress-xdebug:6.0.2-php8.0-apache
    restart: always
    ports:
      - 30000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 1
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./.docker/wp:/var/www/html
      - ./apps/theme:/var/www/html/wp-content/themes/beeclover

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MARIADB_ROOT_PASSWORD: 1

volumes:
  wordpress:
  redis:
